package io.lemonlabs.sigv4

object Services {
  type Service = String
  val appStream: Service = "appstream"
  val autoscaling: Service = "autoscaling"
  val codeCommit: Service = "codecommit"
  val cloudFormation: Service = "cloudformation"
  val cloudfront: Service = "cloudfront"
  val cloudhsm: Service = "cloudhsm"
  val cloudSearch: Service = "cloudsearch"
  val cloudTrail: Service = "cloudtrail"
  val codeDeploy: Service = "codedeploy"
  val cognitoIdentity: Service = "cognito-identity"
  val cognitoSync: Service = "cognito-sync"
  val config: Service = "config"
  val dataPipeline: Service = "datapipeline"
  val directConnect: Service = "directconnect"
  val ec2: Service = "ec2"
  val ecs: Service = "ecs"
  val elasticache: Service = "elasticache"
  val elasticBeanstalk: Service = "elasticbeanstalk"
  val elasticLoadBalancing: Service = "elasticloadbalancing"
  val elasticMapReduce: Service = "elasticmapreduce"
  val elasticSearch: Service = "es"
  val elasticTranscoder: Service = "elastictranscoder"
  val glacier: Service = "glacier"
  val kinesis: Service = "kinesis"
  val kms: Service = "kms"
  val lambda: Service = "lambda"
  val logs: Service = "logs"
  val mobileAnalytics: Service = "mobileanalytics"
  val monitoring: Service = "monitoring"
  val opsworks: Service = "opsworks"
  val route53domains: Service = "route53domains"
  val rds: Service = "rds"
  val redshift: Service = "redshift"
  val route53: Service = "route53"
  val s3: Service = "s3"
  val ses: Service = "ses"
  val sns: Service = "sns"
  val storagegateway: Service = "storagegateway"
  val sts: Service = "sts"
  val swf: Service = "swf"
}
